Web Node/Web Node/Controllers/LogsController.cs
using NodeData;
using NodeData.DTO;
using NodeData.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Web_Node.Classes;

namespace Web_Node.Controllers
{
    [System.Web.Mvc.Authorize]
    public class LogsController : Controller
    {

        //Decorate with a HttpPost meaning it will only ever excute on a HTTP Post operation. If it was ever triggered with a Get it will be ignored. 
        [HttpPost]
        public ActionResult PurgeLogs(string appName, string serverName, string dfrom, string dto, string information, string warning, string error)
        {
            // The Parameters are passed from the ajax function
            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                bool infoChecked = !string.IsNullOrEmpty(information) ? bool.Parse(information) : false;
                bool warnChecked = !string.IsNullOrEmpty(warning) ? bool.Parse(warning) : false;
                bool errChecked = !string.IsNullOrEmpty(error) ? bool.Parse(error) : false;
                //Create a list of APPLOG records to be deleted
                IQueryable<AppLog> logList = uow.AppLogs.GetAll();
                var dellogList = logList.If(!string.IsNullOrEmpty(appName),
                         q => q.Where(x => x.GL_AppName == appName))
                     .If(!string.IsNullOrEmpty(serverName),
                         q => q.Where(x => x.GL_ServerName == serverName))
                     .If(infoChecked,
                         q => q.Where(x => x.GL_MessageType == "Information"))
                     .If(warnChecked,
                         q => q.Where(x => x.GL_MessageType == "Warning"))
                     .If(errChecked,
                         q => q.Where(x => x.GL_MessageType == "Error"))
                     .ToList();


                //logList = !string.IsNullOrEmpty(appName) ? from x in logList
                //                                           where x.GL_AppName == appName
                //                                           select x : logList;
                //uow.AppLogs.RemoveRange(logList.ToList());
                //logList = !string.IsNullOrEmpty(serverName) ? from x in logList
                //                                              where x.GL_ServerName == serverName
                //                                              select x : logList;
                //uow.AppLogs.RemoveRange(logList.ToList());
                //if (!string.IsNullOrEmpty(information))
                //{
                //    if (bool.Parse(information))
                //    {
                //        logList = from x in logList
                //                  where x.GL_MessageType == "Information"
                //                  select x;
                //        uow.AppLogs.RemoveRange(logList.ToList());
                //    }
                //}
                //if (!string.IsNullOrEmpty(warning))
                //{
                //    if (bool.Parse(warning))
                //    {
                //        logList = from x in logList
                //                  where x.GL_MessageType == "Warning"
                //                  select x;
                //        uow.AppLogs.RemoveRange(logList.ToList());
                //    }
                //}
                //if (!string.IsNullOrEmpty(error))
                //{
                //    if (bool.Parse(error))
                //    {
                //        logList = from x in logList
                //                  where x.GL_MessageType == "Error"
                //                  select x;
                //        uow.AppLogs.RemoveRange(logList.ToList());
                //    }
                //}
                //Now we go and collect the records to be deleted and pass it to the DTO (UnitOfWork) to do the Database work. 
                uow.AppLogs.RemoveRange(dellogList);
                uow.Complete();
            }


            return RedirectToAction("Index");
        }
        // GET: Logs
        public ActionResult Index(DateTime? dfrom, DateTime? dto, string ddlApplication, string ddlServer, string cbInformation, string cbWarning, string cbError)
        {
            // The Index function is the default "READ" function and default ACTION for this controller
            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                IList<AppLog> logs;
                //Create a list of distinct Applications
                var apps = uow.AppLogs.GetAll().Select(ap => ap.GL_AppName).Distinct().ToList();
                //Create a list of distinct Servers
                var servers = uow.AppLogs.GetAll().Select(ap => ap.GL_ServerName).Distinct().ToList();
                //Create a new SelectList that will be used to fill the Application Drop down List
                ViewBag.AppList = new SelectList(apps, "GL_AppName");
                // Create a new SelectList that will be used to fill the SERVER drop down list
                ViewBag.ServerList = new SelectList(servers, "GL_ServerName");
                //Set the default Date Ranges
                ViewBag.DFrom = DateTime.Now.AddDays(-7);
                ViewBag.DTo = DateTime.Now;
                //If no Application is passed grab everything in the AppLog table as an IQueryable
                var logList = string.IsNullOrEmpty(ddlApplication) ? uow.AppLogs.GetAll() : uow.AppLogs.Find(x => x.GL_AppName == ddlApplication);
                //Now that we have a logList IQueryable we pass this through the filters to get to the required list. 
                if (!string.IsNullOrEmpty(ddlServer))
                {
                    //Equiv SQL is = Select *  from logList where GL_AppName = "ddlServer Value"
                    logList = from x in logList
                              where x.GL_AppName == ddlServer
                              select x;
                }
                //cb denotes CheckBox. Value is true if checked. 
                if (!string.IsNullOrEmpty(cbInformation))
                {
                    if (bool.Parse(cbInformation))
                    {
                        logList = from x in logList
                                  where x.GL_MessageType == "Information"
                                  select x;
                    }
                }
                if (!string.IsNullOrEmpty(cbWarning))
                {
                    if (bool.Parse(cbWarning))
                    {
                        logList = from x in logList
                                  where x.GL_MessageType == "Warning"
                                  select x;
                    }
                }
                if (!string.IsNullOrEmpty(cbError))
                {
                    if (bool.Parse(cbError))
                    {
                        logList = from x in logList
                                  where x.GL_MessageType == "Error"
                                  select x;
                    }
                }
                

                if(dfrom != null && dto != null)
                {
                    logList = from x in logList
                              where x.GL_Date >= dfrom && x.GL_Date <= dto
                              select x;
                }else if(dfrom != null && dto == null)
                {
                    logList = from x in logList
                              where x.GL_Date >= dfrom
                              select x;
                }
                else if (dfrom == null && dto != null)
                {
                    logList = from x in logList
                              where x.GL_Date <= dto
                              select x;
                }
                else
                {
                    logList = from x in logList
                              where x.GL_Date.Month == DateTime.Now.Month
                    && x.GL_Date.Day == DateTime.Now.Day
                    && x.GL_Date.Year == DateTime.Now.Year
                              select x;
                }


                
                //The process of sending the IQueryable to a List is the actual Read from the Database where data is transferred back to the View. 
                return View(logList.ToList());
            }
        }



    }
}

Web Node/Web Node/Views/Logs/Index.cshtml
@model  List<NodeData.Models.AppLog>

@{
    ViewBag.Title = "Application Logs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles {
    @Styles.Render("https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css")
    @Styles.Render("https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css")

}

@section scripts{
    @Scripts.Render("https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js")
    @*@Scripts.Render("https://code.jquery.com/jquery-3.5.1.js");*@
    @Scripts.Render("https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js")
    @Scripts.Render("https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js")


}
<script type="text/javascript">

    //Ensures that nothing will happen until the whol page has been rendered.
    $(document).ready(function () {
        //jQuery to return the page object called "purgeForm"
        var purgeform = $('#purgeForm');
        //If we click the filter button. Submit the form and return the filter READ function
        $('#filter').click(function () {
            purgeform.submit();
            return false;
        });
        //if we click the Purge Logs button
        $('#purgeLogs').click(function () {
            //Read the state of the checkboxes using jQuery
            var bInfo = false;
            if ($('#cbInformation').is(":checked")) {
                bInfo = true;
            }

            var bWarn = false;
            if ($("#cbWarning").is(":checked")) {
                bWarn = true;
            }

            var bErr = false;
            if ($('#cbError').is(":checked")) {
                bErr = true;
            }
            //Generate the ajax request and serialise the JSON request data.
            $.ajax({
                type: "POST", //Http Method
                url: "PurgeLogs", //  Controller / ActionName
                data: {
                    //Pass the variables to the PurgeLogs method/action
                    appName: $('#ddlApplication').val(),
                    serverName: $('#ddlServer').val(),
                    dfrom: $('#dateFrompicker').val(),
                    dto: $('#dateTopicker').val(),
                    information: bInfo,
                    warning: bWarn,
                    error: bErr
                },
                success: function (data) {

                }
            });
        });
        // Turn off the Search function in the Table. Not needed.
        $('#applicationLogs').DataTable();

    });


</script>
<div class="row align-items-center">
    <div class="col-8 col-md-8"><h2 class="m-0"><i class="fas fa-user-circle mr-2 " style="opacity:0.2;" aria-hidden="true"></i> Application Logs</h2></div>
    <div class="col-4 col-md-4 text-right">
    </div>
</div>
<br />
@*HTML Form Name called purgeForm. Used to create filtered list.*@
@using (Html.BeginForm("Index", "Logs", FormMethod.Get, new { id = "purgeForm" }))
{
    <div class="row">
        <table>
            <tr>
                <td><label>Select Application</label></td>
                @*Application drop down list filled from the unique list of Applications (LogsController Index function)*@
                <td>@Html.DropDownList("ddlApplication", new SelectList(ViewBag.AppList.Items, "GL_AppName"), "none selected", new { @class = "form-control" })</td>
                <td><label>Select Server</label></td>
                @*Server List drop down list filled from the unique list of Servers*@
                <td>@Html.DropDownList("ddlServer", new SelectList(ViewBag.ServerList.Items, "GL_ServerName"), "none selected", new { @class = "form-control" })</td>

            </tr>
            <tr>
                <td><label>From</label></td>
                <td>
                    <div class="input-group date">
                        <input id="dateFrompicker" name="dateFrompicker">

                    </div>
                    <script>
                    var today = new Date();
                    var ddf = String(today.getDate() - 7).padStart(2, '0');
                    var ddt = String(today.getDate()).padStart(2, '0');
                    var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
                    var yyyy = today.getFullYear();
                    var fromDate = ddf + '/' + mm + '/' + yyyy;
                    var toDate = ddt + '/' + mm + '/' + yyyy;
                    $('#dateFrompicker').datepicker({
                        uiLibrary: 'bootstrap4',
                        format: 'dd/mm/yyyy',
                        value: '@ViewBag.DFrom'
                    });
                    $('#dateFrompicker').datepicker
                    </script>
                </td>
                <td><label>To:</label></td>
                <td>
                    <div class="input-group date" data-provide="dateToPicker">
                        <input id="dateToPicker" name="dateToPicker">
                        <script>
                        $('#dateToPicker').datepicker({
                            uiLibrary: 'bootstrap4',
                            format: 'dd/mm/yyyy',
                            value: '@ViewBag.DTo',
                        });
                        ;
                        </script>
                    </div>
                </td>
            </tr>
            <tr>
                <td><label>Include</label></td>
                <td colspan="3">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="true" name="cbInformation" id="cbInformation">
                        <label class="form-check-label" for="cbInformation">Information</label>
                    </div>

                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="true" name="cbWarning" id="cbWarning">
                        <label class="form-check-label" for="cbWarning">Warning</label>
                    </div>


                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="true" name="cbError" id="cbError">
                        <label class="form-check-label" for="cbError">Error</label>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2" align="right">
                    <a href="#" class="btn btn-dark text-nowrap" id="filter">
                        <i class="fas fa-search"></i>Filter
                    </a>
                </td>
                <td colspan="2" align="right">
                    <a href="#" class="btn btn-dark text-nowrap" id="purgeLogs">
                        <i class="fas fa-trash-alt"></i>Purge Logs
                    </a>
                </td>
            </tr>
        </table>
    </div>

}
<div class="container">
    <div class="row">
        <table class="table table-striped table-bordered" id="applicationLogs" width="100%">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Application</th>
                    <th>Server Name</th>
                    <th>Date</th>
                    <th>Process</th>
                    <th>Level</th>
                    <th>Detail</th>
                    <th>Path</th>
                </tr>
            </thead>
            <tbody>
                @*Iterate through the list of AppLogs (Model)*@
                @foreach (var log in Model)
                {
                    <tr>
                        <td>
                            @*Image Selection*@
                            @switch (log.GL_MessageType)
                            {
                                case "Information":
                                    <img src="~/images/information.png" />
                                    break;
                                case "Warning":
                                    <img src="~/images/warning.png" />
                                    break;
                                case "Error":
                                    <img src="~/images/error.png" />
                                    break;
                            }

                        </td>
                        <td>@log.GL_AppName</td>
                        <td class="text-nowrap">@log.GL_ServerName</td>
                        <td class="text-nowrap">@log.GL_Date</td>
                        <td class="text-nowrap">@log.GL_ProcName</td>
                        <td>@log.GL_MessageLevel</td>
                        <td>@log.GL_MessageDetail</td>
                        <td>@log.GL_Path</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>


</div>