Web Node/Web Node/Models/CustomerViewModel.cs
using NodeData.Models;
using System.Collections.Generic;

namespace Web_Node.Models
{
    public class CustomerViewModel
    {
        public IList<Customer> Customers { get; set; }

        public Customer Customer { get; set; }

        public string EditMode { get; set; }
    }
}

Web Node/Web Node/Controllers/CustomerController.cs
using NodeData;
using NodeData.DTO;
using NodeData.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Web_Node.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Web;

namespace Web_Node.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            CustomerViewModel customer = new CustomerViewModel();
            ApplicationUserManager UserManager;
            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                if (User.IsInRole("Administrator"))
                {
                    customer.Customers = uow.Customers.GetAll().OrderBy(x => x.C_NAME).ToList();
                }
                else
                {
                    UserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                    ApplicationUser user = UserManager.FindById(User.Identity.GetUserId());
                    customer.Customers = uow.Customers.Find(x => x.C_CODE == user.CompanyCode).OrderBy(x => x.C_NAME).ToList();

                }
            }
            return View(customer);
        }

        [HttpGet]
        public ActionResult Details(Guid? id)
        {
            var cust = new CustomerViewModel();
            if (id == null)
            {
                cust.EditMode = "New";
                ViewBag.Title = "Add New Customer";
                cust.Customer = new Customer();
                return View(cust);
            }
            ViewBag.Title = "Edit Customer Details";
            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                cust.EditMode = "Edit";
                cust.Customer = uow.Customers.Get((Guid)id);
                return View(cust);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(CustomerViewModel cust, string C_IS_ACTIVE, string C_ON_HOLD)
        {
            //if (cust.EditMode == "New")
            //{
            //    Add(cust);
            //};
            //var id = cust.Customer.C_ID;
            //if (cust.Customer.C_ID == Guid.Empty)
            //{
            //    cust.EditMode = "New";
            //    ViewBag.Title = "Add New Customer";
            //    cust.Customer = new Customer();
            //    return View(cust);
            //}
            //ViewBag.Title = "Edit Customer Details";
            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                var customer = uow.Customers.Get((Guid)cust.Customer.C_ID);

                customer.C_NAME = cust.Customer.C_NAME;
                customer.C_SHORTNAME = cust.Customer.C_SHORTNAME;
                customer.C_CODE = cust.Customer.C_CODE;
                customer.C_PATH = cust.Customer.C_PATH;
                if (C_IS_ACTIVE == "true")
                {
                    customer.C_IS_ACTIVE = "Y";
                }
                else
                {
                    customer.C_IS_ACTIVE = "N";
                }

                if (C_ON_HOLD == "true")
                {
                    customer.C_ON_HOLD = "Y";
                }
                else
                {
                    customer.C_ON_HOLD = "N";
                }

                uow.Complete();
            }

            //return View(cust);
            return RedirectToAction("Index");
        }


        public ActionResult Add(CustomerViewModel cust)
        {
            var newcust = new Customer
            {
                C_CODE = cust.Customer.C_CODE,
                C_NAME = cust.Customer.C_NAME,
                C_SHORTNAME = cust.Customer.C_SHORTNAME,
                C_IS_ACTIVE = cust.Customer.C_IS_ACTIVE,
                C_PATH = cust.Customer.C_PATH,
                C_INVOICED = string.IsNullOrEmpty(cust.Customer.C_INVOICED) ? "N" : cust.Customer.C_INVOICED,
                C_ON_HOLD = string.IsNullOrEmpty(cust.Customer.C_ON_HOLD) ? "N" : cust.Customer.C_ON_HOLD,
                C_FTP_CLIENT = string.IsNullOrEmpty(cust.Customer.C_FTP_CLIENT) ? "N" : cust.Customer.C_FTP_CLIENT,
                C_TRIAL = string.IsNullOrEmpty(cust.Customer.C_TRIAL) ? "N" : cust.Customer.C_TRIAL,
                C_SATELLITE = string.IsNullOrEmpty(cust.Customer.C_SATELLITE) ? "N" : cust.Customer.C_SATELLITE
            };
            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                var existingCustomer = uow.Customers.Find(x => x.C_NAME == cust.Customer.C_NAME || x.C_CODE == cust.Customer.C_CODE || x.C_SHORTNAME == cust.Customer.C_SHORTNAME).FirstOrDefault();
                if (existingCustomer != null)
                {
                    return RedirectToAction("Details");

                }
                uow.Customers.Add(newcust);
                uow.Complete();

            }
            return RedirectToAction("Details", newcust.C_ID.ToString());
        }


        [HttpGet]
        public ActionResult ProfileListing(Guid custId)
        {
            List<Profile> profiles = new List<Profile>();
            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                profiles = uow.Profiles.Find(x => x.P_C == custId)
                    .OrderBy(x => x.P_SENDERID)
                    .ThenBy(x => x.P_RECIPIENTID)
                    .ToList();
            }

            return PartialView(profiles);
        }


    }
}

Web Node/Web Node/Controllers/ProfileController.cs
using NodeData;
using NodeData.DTO;
using NodeData.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using Web_Node.Models;
using Microsoft.AspNet.Identity;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;

namespace Web_Node.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        [HttpGet]
        public ActionResult Index(Guid? id)
        {

            ProfileViewModel profile = new ProfileViewModel();
            ApplicationUserManager UserManager;

            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                if(id != null)
                {
                    profile.Profiles = uow.CustProfiles.Find(x => x.P_C == (Guid)id).OrderBy(x => x.C_NAME).ToList();
                }
                else
                {
                    if (User.IsInRole("Administrator"))
                    {
                        profile.Profiles = uow.CustProfiles.GetAll().OrderBy(x => x.C_NAME).ToList();
                    }
                    else
                    {
                        UserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                        ApplicationUser user = UserManager.FindById(User.Identity.GetUserId());
                        profile.Profiles = uow.CustProfiles.Find(x => x.C_CODE == user.CompanyCode).OrderBy(x => x.C_NAME).ToList();

                    }
                    
                }
                
            }
            return View(profile);
        }

        [HttpGet]
        public ActionResult Tasklist(Guid? id, DateTime? from = null, DateTime? to = null)
        {
            ViewBag.from = "";
            ViewBag.to = "";
            var task = new TaskListViewModel();
            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                if (from != null && to != null)
                {
                    TimeSpan tFrom = new TimeSpan(0, 0, 0);
                    DateTime dFrom = Convert.ToDateTime(from) + tFrom;
                    TimeSpan tTo = new TimeSpan(23, 59, 59);
                    DateTime dTo = Convert.ToDateTime(to) + tTo;
                    task.Tasks = uow.TaskLists.Find(x => x.TL_P == (Guid)id && x.TL_ReceiveDate >= dFrom && x.TL_ReceiveDate <= dTo).OrderByDescending(x => x.TL_ReceiveDate).ToList();
                }
                else
                {
                    task.Tasks = uow.TaskLists.Find(x => x.TL_P == (Guid)id 
                    && x.TL_ReceiveDate.Value.Month == DateTime.Now.Month
                    && x.TL_ReceiveDate.Value.Day == DateTime.Now.Day
                    && x.TL_ReceiveDate.Value.Year == DateTime.Now.Year
                    ).OrderByDescending(x => x.TL_ReceiveDate).ToList();
                }
                task.Profile = uow.Profiles.Get((Guid)id);
            }
            if(from != null)
            {
                ViewBag.from = from.Value.ToString("yyyy-MM-dd");
            }

            if (to != null)
            {
                ViewBag.to = to.Value.ToString("yyyy-MM-dd");
            }

            return View(task);
        }

        // GET: Profile/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Profile/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Profile/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Profile/Edit/5
        [HttpGet]
        public ActionResult Edit(Guid? id)
        {
            ProfileViewModel profile = new ProfileViewModel();
            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                profile.Profile = new Profile();
                profile.CustProfile = uow.CustProfiles.Find(x => x.P_ID == (Guid)id).FirstOrDefault();
                profile.Profile = uow.Profiles.Find(x => x.P_ID == (Guid)id).FirstOrDefault();
            }

            ViewBag.P_MSGTYPE = new SelectList(new[] { "Original", "Response", "Forward", "eAdapter", "Conversion", "PDF2XML" });
            ViewBag.P_BILLTO = new List<SelectListItem>() { new SelectListItem { Value = profile.CustProfile.C_CODE, Text = profile.CustProfile.C_CODE + "(Customer)" }, new SelectListItem { Value = profile.Profile.P_RECIPIENTID, Text = profile.Profile.P_RECIPIENTID+"(Vendor)" } };
            ViewBag.P_DIRECTION = new List<SelectListItem>() { new SelectListItem { Value = "R", Text = "Receive" }, new SelectListItem { Value = "S", Text = "Send" } };
            return View(profile);
        }

        // POST: Profile/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Profile model)
        {

            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                var prof = uow.Profiles.Get((Guid)model.P_ID);

                prof.P_DESCRIPTION = model.P_DESCRIPTION;
                prof.P_SENDERID = model.P_SENDERID;
                prof.P_RECIPIENTID = model.P_RECIPIENTID;
                prof.P_REASONCODE = model.P_REASONCODE;
                prof.P_EVENTCODE = model.P_EVENTCODE;
                prof.P_SUBJECT = model.P_SUBJECT;
                prof.P_MSGTYPE = model.P_MSGTYPE;
                prof.P_DIRECTION = model.P_DIRECTION;
                prof.P_BILLTO = model.P_BILLTO;
                if (model.P_ACTIVE == "true")
                {
                    prof.P_ACTIVE = "Y";
                }
                else
                {
                    prof.P_ACTIVE = "N";
                }
                
                prof.P_SERVER = model.P_SERVER;
                prof.P_PORT = model.P_PORT;
                prof.P_PATH = model.P_PATH;
                prof.P_USERNAME = model.P_USERNAME;
                if (model.P_SSL == "true")
                {
                    prof.P_SSL = "Y";
                }
                else
                {
                    prof.P_SSL = "N";
                }
                prof.P_LIBNAME = model.P_LIBNAME;
                prof.P_METHOD = model.P_METHOD;
                prof.P_PARAMLIST = model.P_PARAMLIST;

                uow.Complete();

            }

                return RedirectToAction("Index");
           
        }

        // GET: Profile/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Profile/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Web Node/Web Node/Views/Customer/Details.cshtml
@model Web_Node.Models.CustomerViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@section styles {
    @Styles.Render("https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css")
    @Styles.Render("https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css")


}

@section scripts{
    @Scripts.Render("https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js")
    @*@Scripts.Render("https://code.jquery.com/jquery-3.5.1.js");*@
    @Scripts.Render("https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js")
    @Scripts.Render("https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js")

}
<div class="row align-items-center">
    <div class="col-8 col-md-8"><h2 class="m-0"><i class="fas fa-users mr-2 " style="opacity:0.2;" aria-hidden="true"></i> Customers Details</h2></div>
   <div class="col-4 col-md-4 text-right">
        <a href="/Customer/Index" class="btn bg-white text-dark"><i class="fas mr-2 fa-arrow-left" aria-hidden="true"></i><span> Back to List</span></a>
   </div>
</div>
<br />
@using (Html.BeginForm("Details", "Customer", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    var buttonText = Model.EditMode == "New" ? "Add " : "Update ";
    buttonText += "Customer";
    @Html.HiddenFor(x => x.EditMode)

    <div class="panel bg-white px-4 py-4 form-horizontal">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="Customer_C_NAME" class="control-label">Customer Name</label>
                    @Html.EditorFor(x => x.Customer.C_NAME, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label" for="Customer_C_CODE">Customer Code</label>
                    @Html.EditorFor(x => x.Customer.C_CODE, new { htmlAttributes = new { @class = "form-control", @style = "text-transform: uppercase;" } })
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label">Short Name</label>
                    @Html.EditorFor(x => x.Customer.C_SHORTNAME, new { htmlAttributes = new { @class = "form-control", @style = "text-transform: uppercase;" } })
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label d-block" for="Customer_C_PATH">Customer Path</label>
                    @* @Html.EditorFor(x => x.Customer.C_PATH, new { htmlAttributes = new {  @class = "form-control" } })*@
                    @Html.TextBoxFor(x => x.Customer.C_PATH, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-4">
                <label class="control-label">&nbsp;</label>
                <div class="btn bg-light d-flex align-items-center">
                    <div class="pt-2">
                        <span class="form-checkbox">@Html.CheckBox("C_IS_ACTIVE", Model.Customer.C_IS_ACTIVE == "Y" ? true : false, new { })</span>
                    </div>
                    <div>
                        <label class="text-nowrap my-0 control-label pl-3" for="C_ISACTIVE">Is Active</label>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <label class="control-label">&nbsp;</label>
                <div class="btn bg-light d-flex align-items-center">
                    <div class="pt-2">
                        <span class="form-checkbox"> @Html.CheckBox("C_ON_HOLD", Model.Customer.C_ON_HOLD == "Y" ? true : false, new { })</span>
                    </div>
                    <div>
                        <label class="text-nowrap my-0 control-label pl-3" for="C_ON_HOLD">On Hold</label>
                    </div>
                </div>
            </div>
        </div>
        <br/>
        <div class="row justify-content-end">
            <div class="col">
                <button type="submit" class="btn btn-primary"><i class="fas fa-save mr-2 "></i> @buttonText</button>
            </div>

        </div>
    </div>
    <br/>

    
    @Html.HiddenFor(x => x.Customer.C_ID)






}

Web Node/Web Node/Views/Customer/Index.cshtml
@model Web_Node.Models.CustomerViewModel

@{
    ViewBag.Title = "Customers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles {
    @Styles.Render("https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css")
    @Styles.Render("https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css")

}

@section scripts{
    @Scripts.Render("https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js")
    @*@Scripts.Render("https://code.jquery.com/jquery-3.5.1.js");*@
    @Scripts.Render("https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js")
    @Scripts.Render("https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js")




<script type="text/javascript">

    //Ensures that nothing will happen until the whol page has been rendered.
    $(document).ready(function () {
        $('#customerList').DataTable();
    });


</script>
}
<div class="row align-items-center">
    <div class="col-8 col-md-8"><h2 class="m-0"><i class="fas fa-users mr-2 " style="opacity:0.2;" aria-hidden="true"></i> Customers</h2></div>

    @if (User.IsInRole("Administrator"))
    {
        <div class="col-4 col-md-4 text-right">
            <a href="@Url.Action("Details", "Customer")" class="btn btn-primary"><i class="fas fa-plus mr-2"></i> <span>Add Customer</span></a>
        </div>
    }

</div>
<br/>

<div class="table-responsive">
    <table id="customerList" class="table  ">
        <thead>
            <tr>
                <th>Customer Name</th>
                <th>Customer code</th>
                <th>Short Name</th>
                <th>Is Active</th>
                <th>Has Satellite</th>
                <th>Profiles</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cust in Model.Customers)
            {
            <tr>
                <td>
                    <a href="@Url.Action("Details", "Customer", new { @id = @cust.C_ID }, null)" class="text-dark">
                        <div class="d-flex align-items-center">
                            <div><span class="icon-circle  bg-transparent"><i  class="  fa fa-users" aria-hidden="true"></i></span></div>
                            <div class="px-2">
                                <strong>
                                    @cust.C_NAME
                                </strong>
                            </div>
                        </div>
                    </a>
                </td>

                <td>@cust.C_CODE</td>
                <td>@cust.C_SHORTNAME</td>
                <td class="text-center">
                    <label class="form-checkbox d-none">
                        @Html.CheckBox("C_IS_ACTIVE", cust.C_IS_ACTIVE == "Y" ? true : false, new { @disabled = "disabled" })
                    </label>
                    @{
                        if (cust.C_IS_ACTIVE == "Y")
                        {
                            <span class="badge d-block py-1 fs-14 badge-danger">ACTIVE</span>
                        }
                        else
                        {
                            <span class="badge d-block py-1 fs-14 badge-light">INACTIVE</span>
                        }
                    }


                </td>
                <td>
                    <label class="form-checkbox d-none">
                        @Html.CheckBox("C_SATELLITE", cust.C_SATELLITE == "Y" ? true : false, new { @disabled = "disabled" })
                    </label>
                    @{
                        if (cust.C_SATELLITE == "Y")
                        {
                            <span class="badge d-block py-1 fs-14 badge-danger">HAS SATELLITE</span>
                        }
                        else
                        {
                           
                        }
                    }
                </td>
                <td>
                    <div class="d-flex align-items-center">
                        <div class="ml-auto"> <a href="@Url.Action("Index", "Profile", new { @id = @cust.C_ID }, null)" class="d-block text-primary mx-1" data-toggle="tooltip" data-placement="top" title="Profiles"><span class="icon-circle"><i style="opacity:1;" class="text-primary fa fa-arrow-right" aria-hidden="true"></i></span></a></div>
                    </div>
                </td>
            </tr>
            }
        </tbody>

    </table>
</div>

Web Node/Web Node/Views/Customer/ProfileListing.cshtml
@model List<NodeData.Models.Profile>

<script type="text/javascript">

    //Ensures that nothing will happen until the whol page has been rendered.
    $(document).ready(function () {
        $('#profileList').DataTable(
            {
                "stripeClasses": []

            });
    });


</script>

<div class="table-responsive">
    <table id="profileList" class="table  compact">
        <thead>
            <tr>

                <th>Is Active</th>
                <th>Description</th>
                <th>Sender ID</th>
                <th>Recipient ID</th>
                <th>Method</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var profile in Model)
            {
                <tr class=@(profile.P_DIRECTION=="S"?"send":"receive")>

                    <td>
                        <label class="d-none"> @Html.CheckBox("P_IsActive", profile.P_ACTIVE == "Y" ? true : false, new { @disabled = "disabled" })</label>
                        @{
                            if (profile.P_ACTIVE == "Y")
                            {
                                <span class="badge d-block py-1 fs-14 badge-danger">ACTIVE</span>
                            }
                            else
                            {
                                <span class="badge d-block py-1 fs-14 badge-light">INACTIVE</span>
                            }
                        }
                    </td>
                    <td>@profile.P_DESCRIPTION</td>
                    <td>@profile.P_SENDERID</td>
                    <td>@profile.P_RECIPIENTID</td>
                    <td>
                        @switch (profile.P_DELIVERY)
                        {
                            case "R":
                                <img src="~/images/folder.png" title="FTP Receive" />
                                break;
                            case "E":
                                <img src="~/images/email.png" title="Email" />
                                break;
                            case "D":
                                <img src="~/images/ftp.png" title="FTP Direct" />
                                break;
                            case "C":
                                <img src="~/images/connector.png" title="CTC Connector" height="32" width="32" />
                                break;
                            case "P":
                                <img src="~/images/folder.png" title="Pickup" />
                                break;
                            case "S":
                                <img src="~/images/soap.png" title="RESTFull/Soap" />
                                break;
                        }

                        @profile.P_DELIVERY
                    </td>


                </tr>
            }
        </tbody>
    </table>
</div>