Web Node/Web Node/Models/TransactionsViewModel.cs
using NodeData.Models;
using System;
using System.Collections.Generic;

namespace Web_Node.Models
{
    public class CustomerList
    {
        public string CustomerName { get; set; }
        public Guid Id { get; set; }
    }

    public class ProfileList
    {
        public string Profiledescription { get; set; }
        public Guid Id { get; set; }
    }

    public class TransactionsViewModel
    {
        public IEnumerable<CustomerList> Customers { get; set; }
        public IEnumerable<ProfileList> CustomersProfiles { get; set; }
        public IEnumerable<TaskList> Tasklists { get; set; }
        public IEnumerable<ApiLog> ApiLogs { get; set; }




    }
}

Web Node/Web Node/Controllers/TransactionsController.cs
using NodeData;
using NodeData.DTO;
using NodeData.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Web_Node.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Web;

namespace Web_Node.Controllers
{

    [System.Web.Mvc.Authorize]
    public class TransactionsController : Controller
    {
        // GET: Transactions
        public async Task<ActionResult> Index()
        {

            var customerList = await GetCustomersAsync();

            
            ViewBag.CustomerList = new SelectList(customerList, "CustomerName", "Id");

            return View();
        }

        public async Task<List<CustomerList>> GetCustomersAsync()
        {

            ApplicationUserManager UserManager;
            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                if (User.IsInRole("Administrator"))
                {
                    var customers = uow.Customers.Find(x => x.C_IS_ACTIVE == "Y")
                                .Select(y => new CustomerList
                                {
                                    CustomerName = y.C_NAME,
                                    Id = y.C_ID
                                })
                                .OrderBy(c => c.CustomerName);
                    return await customers.ToListAsync();
                }
                else
                {
                    UserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                    ApplicationUser user = UserManager.FindById(User.Identity.GetUserId());
                    var customers = uow.Customers.Find(x => x.C_IS_ACTIVE == "Y" && x.C_CODE == user.CompanyCode)
                                .Select(y => new CustomerList
                                {
                                    CustomerName = y.C_NAME,
                                    Id = y.C_ID
                                })
                                .OrderBy(c => c.CustomerName);
                    return await customers.ToListAsync();
                }
                

                

            }


        }

        private async Task<JsonResult> GetProfileListAsync(Guid custid)
        {
            using (IUnitOfWork uow = new UnitOfWork(new NodeDataContext()))
            {
                var profileList = await uow.Profiles.Find(x => x.P_C == custid)
                                        .Select(y => new ProfileList
                                        {
                                            Profiledescription = y.P_DESCRIPTION,
                                            Id = y.P_ID
                                        })
                                   .OrderBy(x => x.Profiledescription).ToListAsync();
                var li = new List<SelectListItem>();
                foreach (var p in profileList)
                {
                    li.Add(new SelectListItem { Text = p.Profiledescription, Value = p.Id.ToString() });
                }

                return Json(li, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult FindTransactions(string CustID, FormCollection formValues)
        {


            return RedirectToAction("Index");
        }



    }
}

Web Node/Web Node/Views/Transactions/Index.cshtml
@model Web_Node.Models.TransactionsViewModel


@{
    ViewBag.Title = "Find Transactions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles {
    @Styles.Render("https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css")
    @Styles.Render("https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css")

}

@section Scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            $('#CustomerSelect').change(function () {
                var selectedCustomer = $("#CustomerSelect").val();
                var profileSelect = $('#Profile');
                profileSelect.empty();
                if (selectedCustomer != null && selectedCustomer != '') {
                    $.getJSON("/Transactions/GetProfileListAsync", { custid: selectedCustomer },
                        function (profiles) {
                            if (profiles != null && !jQuery.isEmptyObject(profiles)) {
                                profileSelect.append($('<option/>', { value: null, text: "" }));

                                $.each(profiles, function (index, profiles) {
                                    profileSelect.append($('<option/>', {
                                        value: profiles.Value,
                                        text: profiles.Text
                                    }));
                                });
                            };
                        });
                }
            });
        });
    </script>
}

<div class="row align-items-center">
    <div class="col-8 col-md-8"><h2 class="m-0"><i class="fas fa-file-medical-alt mr-2 " style="opacity:0.2;" aria-hidden="true"></i> Transactions</h2></div>
    <div class="col-4 col-md-4 text-right">

    </div>
</div>
<br />
@using (Html.BeginForm("FindTransactions", "Transactions", FormMethod.Post))
{
    <div class="panel bg-white px-4 py-4 form-horizontal">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label">Select Customer</label>
                    @Html.DropDownListFor(c => c.Customers, new SelectList(ViewBag.CustomerList.Items, "Id", "CustomerName"), "none selected", new { @class = "form-control", @id = "CustomerSelect" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label">Select Profile</label>
                    @Html.DropDownList("ProfileSelect", new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } }, "(none selected)", new { @class = "form-control" })
                </div>
            </div>

        </div>
        </div>

        }